# Generated by Django 2.2.2 on 2019-06-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=2000, null=True, verbose_name='username')),
                ('phone', models.CharField(blank=True, max_length=2000, null=True, verbose_name='phone')),
            ],
        ),
    ]
